# Generated by Django 4.2.17 on 2024-12-08 22:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leave",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_leave", "Can approve leave requests"),
                    ("can_reject_leave", "Can reject leave requests"),
                ],
                "verbose_name": "Leave",
                "verbose_name_plural": "Leaves",
            },
        ),
        migrations.AlterModelOptions(
            name="leavebalance",
            options={
                "ordering": ["-year", "leave_type"],
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
            },
        ),
        migrations.AlterField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="accounts.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("ANNUAL", "Annual Leave"),
                    ("SICK", "Sick Leave"),
                    ("UNPAID", "Unpaid Leave"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="accounts.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("ANNUAL", "Annual Leave"),
                    ("SICK", "Sick Leave"),
                    ("UNPAID", "Unpaid Leave"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="total_days",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="used_days",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="year",
            field=models.IntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["employee", "status", "start_date"],
                name="leave_leave_employe_6e9b5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["leave_type", "status"], name="leave_leave_leave_t_3d9af3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(
                fields=["employee", "year"], name="leave_leave_employe_18fb87_idx"
            ),
        ),
    ]
