# Generated by Django 5.1.2 on 2024-10-30 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approuvé par",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Commentaires"),
        ),
        migrations.AddField(
            model_name="notification",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AddField(
            model_name="notification",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("missing_presence", "Présence Manquante"),
                    ("anomaly", "Anomalie"),
                    ("general", "Général"),
                    ("early_departure", "Abandon de Poste"),
                    ("missed_scan", "Oubli de Scan"),
                    ("extended_break", "Pause Prolongée"),
                ],
                max_length=50,
                verbose_name="Type de notification",
            ),
        ),
    ]
