# Generated by Django 5.1.2 on 2024-10-30 06:01

import presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0002_notification_approved_by_notification_comments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reportfolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du rapport"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("presence", "Présence"),
                            ("department", "Département"),
                            ("user", "Utilisateur"),
                        ],
                        max_length=50,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=presence.models.report_file_path,
                        verbose_name="Fichier du rapport",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("pdf", "PDF"), ("xlsx", "Excel")],
                        default="csv",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("generating", "Génération en cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message d'erreur"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Quotidien"),
                    ("WEEKLY", "Hebdomadaire"),
                    ("MONTHLY", "Mensuel"),
                    ("QUARTERLY", "Trimestriel"),
                    ("ANNUAL", "Annuel"),
                ],
                max_length=20,
                verbose_name="Fréquence",
            ),
        ),
    ]
