# Generated by Django 5.1.2 on 2024-10-30 15:43

import presence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0004_temporaryqrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=presence.models.user_profile_image_path,
                verbose_name="Photo de profil",
            ),
        ),
    ]
